#!/bin/bash

cp core.f core.pretty.f && gforth -e 'use core.pretty.f  : empty-block?   true swap  block 1024 0 do  dup i + c@  32 <> if drop false swap leave then loop  drop  ;  : first-empty-block   1000 0 do i empty-block? if i leave then loop ; : line-ends!  block  17 1 do  dup i 64 * 1- + 10 swap c! loop  drop ; : file-line-ends!  first-empty-block 0 do i line-ends! update flush loop ; file-line-ends! bye' && git diff -- . ':(exclude)core.f'
